FROM python:3.11-slim

WORKDIR /app

COPY streaming/requirements.producer.txt .
RUN pip install --no-cache-dir -r requirements.producer.txt

COPY common/ common/
COPY streaming/ streaming/

CMD ["python", "-m", "streaming.kafka_producer"]